version: "3.7"

services:
    database:
        image: postgres
        container_name: database
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=diet_db
volumes:
    pgdata:
        driver: local